spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding:
      true

zuul:
  routes:
    atm-finder:
      path: /atm-finder/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
